default:
  image: ubuntu:focal
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - export PATH=/opt/conda/bin:$PATH
    - apt-get update && apt-get install -y git procps freeglut3-dev libglu1-mesa unzip
    - git clone https://github.com/yxqd/dotmantid ~/.mantid
    - apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates curl git && apt-get clean && rm -rf /var/lib/apt/lists/*
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh && /opt/conda/bin/conda clean -tipsy && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && echo "conda activate base" >> ~/.bashrc 
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - export PATH=/opt/conda/bin:$PATH
    - conda env list
    - conda config --add channels conda-forge 
    - conda config --add channels diffpy 
    - conda config --add channels mantid 
    - conda config --add channels mcvine 
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1 cupy cudatoolkit=11.2.2
    # - nvidia-smi
