.build-job-using-shell:
  tags:
    - shell
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
    - export PATH=/opt/miniconda3/bin:$PATH
    - conda config --add channels conda-forge
    - conda config --add channels diffpy
    - conda config --add channels mcvine
    - conda config --show channels
    - conda remove --name testenv --all
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1
    - conda install -n testenv cupy cudatoolkit=11.3
    - conda run -n testenv python setup.py sdist
    - conda run -n testenv pip install --no-deps .
    - conda run -n testenv python tests/geometry/test_onbox.py

build-job-using-docker:
  tags:
    - docker
  image: nvidia/cuda:11.3.0-devel-ubuntu20.04
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
