.build-job-using-shell:
  tags:
    - shell
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
    - export PATH=/opt/miniconda3/bin:$PATH
    - conda config --add channels conda-forge
    - conda config --add channels diffpy
    - conda config --add channels mcvine
    - conda config --show channels
    - conda remove --name testenv --all
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1
    - conda install -n testenv cupy cudatoolkit=11.3
    - conda run -n testenv python setup.py sdist
    - conda run -n testenv pip install --no-deps .
    - conda run -n testenv python tests/geometry/test_onbox.py

build-job-using-docker:
  tags:
    - docker
  image: nvidia/cuda:11.3.0-devel-ubuntu20.04
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
    - export LANG=C.UTF-8  LC_ALL=C.UTF-8  PATH=/opt/conda/bin:$PATH
    - apt-get update && apt-get install -y git procps freeglut3-dev libglu1-mesa unzip
    - apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates curl git && apt-get clean && rm -rf /var/lib/apt/lists/*
    - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh && /opt/conda/bin/conda clean -tipsy && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && echo "conda activate base" >> ~/.bashrc 
    - export PATH=/opt/conda/bin:$PATH
    - conda env list
    - conda config --add channels conda-forge 
    - conda config --add channels diffpy 
    - conda config --add channels mcvine 
    - conda config --show channels
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1
    - conda install -n testenv cupy cudatoolkit
    - git clone https://github.com/yxqd/dotmantid ~/.mantid
    - conda run -n testenv mcvine
    - conda run -n testenv python setup.py sdist
    - conda run -n testenv pip install --no-deps .
    - conda run -n testenv python tests/geometry/test_onbox.py
