.build-job-using-shell:
  tags:
    - shell
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
    - export PATH=/opt/miniconda3/bin:$PATH
    - conda config --add channels conda-forge
    - conda config --add channels diffpy
    - conda config --add channels mcvine
    - conda config --show channels
    - conda remove --name testenv --all
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1
    - conda install -n testenv cupy cudatoolkit=11.3
    - conda run -n testenv python setup.py sdist
    - conda run -n testenv pip install --no-deps .
    - conda run -n testenv python tests/geometry/test_onbox.py

build-job-using-docker:
  tags:
    - docker
  image: $CI_REGISTRY/mcvine/acc:latest
  cache:
    paths:
      - .conda_pkgs/
      - .conda_envs/
  stage: build
  script:
    - echo "GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN HOME=$HOME PATH=$PATH"
    - nvidia-smi
    - export LANG=C.UTF-8  LC_ALL=C.UTF-8  PATH=/opt/conda/bin:$PATH
    - export PATH=/opt/conda/bin:$PATH
    - conda env list
    - conda config --add channels conda-forge 
    - conda config --add channels diffpy 
    - conda config --add channels mcvine 
    - conda config --show channels
    - conda config --add pkgs_dirs .conda_pkgs/
    - conda config --add envs_dirs .conda_envs/
    - conda create -n testenv python=3.8 mcvine=1.4.4 numba=0.53.1 pytest
    - conda install -n testenv cupy cudatoolkit
    - git clone https://github.com/yxqd/dotmantid ~/.mantid
    - conda run -n testenv mcvine
    - conda run -n testenv python setup.py sdist
    - conda run -n testenv pip install --no-deps .
    - cd tests
    - conda run -n testenv py.test
