name: CI

env: {}

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 17 * * *"
  workflow_dispatch:
      
jobs:
  build-and-test-self-hosted:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ~/.mantid
        run: git clone https://github.com/yxqd/dotmantid ~/.mantid

      # setup conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: testenv
          python-version: ${{ matrix.python-version }}
          channels: mcvine,conda-forge

