name: CI

env: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 17 * * *"
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: install glut
        run: sudo apt-get update && sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip
        
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ~/.mantid
        run: git clone https://github.com/yxqd/dotmantid ~/.mantid

      # setup conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: testenv
          python-version: ${{ matrix.python-version }}
          channels: mcvine/label/unstable,mcvine,mantid/label/nightly,mantid,diffpy,conda-forge

      # install deps and build
      - name: install / build
        shell: pwsh
        run: |
          conda install pytest pytest-cov coveralls openmpi mcvine=1.4.4
          python -c "import matplotlib; import mantid"
          mcvine
          conda install numba=0.53.1 cupy cudatoolkit=11.2.2
          python setup.py sdist
          pip install --no-deps .
      # test
      - name: test
        shell: pwsh
        run: |
          cd tests
          py.test
