name: CI

env: {}

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 17 * * *"
  workflow_dispatch:
      
jobs:
  build-and-test-self-hosted:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # setup conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: testenv
          python-version: ${{ matrix.python-version }}
          channels: mcvine,conda-forge

      # use mamba solver
      - name: use mamba solver in conda
        run: |
          # conda update -n base conda
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba

