name: CI

env: {}

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 17 * * *"
  workflow_dispatch:
      
jobs:
  build-and-test-self-hosted:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # install deps and build
      - name: install / build
        run: |
          conda create -n testenv python=${{ matrix.python-version }}
          conda init
          conda activate testenv
          conda install pytest pytest-cov coveralls openmpi mcvine-core=1.4.9
          python -c "import matplotlib; import mantid"
          mcvine
          conda install numba=0.53.1 cupy cudatoolkit=11.2.2
          python setup.py sdist
          pip install --no-deps .
          python -m "mcvine.acc.patch_numba"
